route:
  receiver: 'telegram-alerts'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'telegram-alerts'
  webhook_configs:
  - url: 'http://telegram-bot:5000/alert'
    send_resolved: true
    max_alerts: 10
    http_config:
      follow_redirects: true
