server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://localhost/loki/api/v1/push
    tls_config:
      insecure_skip_verify: true
    batchwait: 1s
    batchsize: 1


scrape_configs:
- job_name: system
  syslog:
    listen_address: 0.0.0.0:1514
    labels:
      job: "syslog"
      namespace: "default" 
      pod: "my-pod"        
      stream: "stdout"     
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
    - source_labels: ['__syslog_message_severity']
      target_label: 'level'
    - source_labels: ['__syslog_message_app_name']
      target_label: 'application'

- job_name: sql_query_log
  static_configs:
    - targets: ['localhost']
      labels:
        job: sql_query_log
        source: mssql_exporter
        level: info
        __path__: /app/logs/queries.log

- job_name: block_prediction
  static_configs:
    - targets: ['localhost']
      labels:
        job: block_prediction
        __path__: /app/logs/block_prediction.log

- job_name: simulated_test_logs_alt
  static_configs:
    - targets: ['localhost']
      labels:
        job: simulated_test_logs_alt
        source: test_generator
        level: info
        __path__: /app/test_logs/test_alt.log

