server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push    # Дублирование в Telegram
    batchwait: 1s                          # Минимальная задержка
    batchsize: 1  

scrape_configs:
- job_name: system
  syslog:
    listen_address: 0.0.0.0:1514
    labels:
      job: "syslog"
      namespace: "default"  # Пример добавления метки "namespace"
      pod: "my-pod"         # Пример добавления метки "pod"
      stream: "stdout"      # Пример добавления метки "stream"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'host'
    - source_labels: ['__syslog_message_severity']
      target_label: 'level'
    - source_labels: ['__syslog_message_app_name']
      target_label: 'application'

- job_name: sql_query_log
  static_configs:
    - targets: ['localhost']
      labels:
        job: sql_query_log
        source: mssql_exporter
        level: info
        __path__: /app/logs/queries.log

- job_name: block_prediction
  static_configs:
    - targets: ['localhost']
      labels:
        job: block_prediction
        __path__: /app/logs/block_prediction.log
