//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberrySampleLogging
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Activity.
    /// </summary>
    // *** Start programmer edit section *** (Activity CustomAttributes)

    // *** End programmer edit section *** (Activity CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ActivityE", new string[] {
            "activityName as \'Название мероприятия\'",
            "avaluable as \'Доступно\'"})]
    [View("ActivityL", new string[] {
            "activityName as \'Название мероприятия\'",
            "avaluable as \'Доступно\'"})]
    public class Activity : ICSSoft.STORMNET.DataObject
    {
        
        private string factivityName;
        
        private bool favaluable;
        
        // *** Start programmer edit section *** (Activity CustomMembers)

        // *** End programmer edit section *** (Activity CustomMembers)

        
        /// <summary>
        /// activityName.
        /// </summary>
        // *** Start programmer edit section *** (Activity.activityName CustomAttributes)

        // *** End programmer edit section *** (Activity.activityName CustomAttributes)
        [StrLen(255)]
        public virtual string activityName
        {
            get
            {
                // *** Start programmer edit section *** (Activity.activityName Get start)

                // *** End programmer edit section *** (Activity.activityName Get start)
                string result = this.factivityName;
                // *** Start programmer edit section *** (Activity.activityName Get end)

                // *** End programmer edit section *** (Activity.activityName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.activityName Set start)

                // *** End programmer edit section *** (Activity.activityName Set start)
                this.factivityName = value;
                // *** Start programmer edit section *** (Activity.activityName Set end)

                // *** End programmer edit section *** (Activity.activityName Set end)
            }
        }
        
        /// <summary>
        /// avaluable.
        /// </summary>
        // *** Start programmer edit section *** (Activity.avaluable CustomAttributes)

        // *** End programmer edit section *** (Activity.avaluable CustomAttributes)
        public virtual bool avaluable
        {
            get
            {
                // *** Start programmer edit section *** (Activity.avaluable Get start)

                // *** End programmer edit section *** (Activity.avaluable Get start)
                bool result = this.favaluable;
                // *** Start programmer edit section *** (Activity.avaluable Get end)

                // *** End programmer edit section *** (Activity.avaluable Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Activity.avaluable Set start)

                // *** End programmer edit section *** (Activity.avaluable Set start)
                this.favaluable = value;
                // *** Start programmer edit section *** (Activity.avaluable Set end)

                // *** End programmer edit section *** (Activity.avaluable Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ActivityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ActivityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ActivityE", typeof(IIS.FlexberrySampleLogging.Activity));
                }
            }
            
            /// <summary>
            /// "ActivityL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ActivityL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ActivityL", typeof(IIS.FlexberrySampleLogging.Activity));
                }
            }
        }
    }
}
