//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberrySampleLogging
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Group.
    /// </summary>
    // *** Start programmer edit section *** (Group CustomAttributes)

    // *** End programmer edit section *** (Group CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("GroupE", new string[] {
            "groupName as \'Название группы\'"})]
    [View("GroupL", new string[] {
            "groupName as \'Название группы\'"})]
    public class Group : ICSSoft.STORMNET.DataObject
    {
        
        private string fgroupName;
        
        // *** Start programmer edit section *** (Group CustomMembers)

        // *** End programmer edit section *** (Group CustomMembers)

        
        /// <summary>
        /// groupName.
        /// </summary>
        // *** Start programmer edit section *** (Group.groupName CustomAttributes)

        // *** End programmer edit section *** (Group.groupName CustomAttributes)
        [StrLen(255)]
        public virtual string groupName
        {
            get
            {
                // *** Start programmer edit section *** (Group.groupName Get start)

                // *** End programmer edit section *** (Group.groupName Get start)
                string result = this.fgroupName;
                // *** Start programmer edit section *** (Group.groupName Get end)

                // *** End programmer edit section *** (Group.groupName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Group.groupName Set start)

                // *** End programmer edit section *** (Group.groupName Set start)
                this.fgroupName = value;
                // *** Start programmer edit section *** (Group.groupName Set end)

                // *** End programmer edit section *** (Group.groupName Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "GroupE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GroupE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GroupE", typeof(IIS.FlexberrySampleLogging.Group));
                }
            }
            
            /// <summary>
            /// "GroupL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View GroupL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("GroupL", typeof(IIS.FlexberrySampleLogging.Group));
                }
            }
        }
    }
}
