//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.FlexberrySampleLogging
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Student.
    /// </summary>
    // *** Start programmer edit section *** (Student CustomAttributes)

    // *** End programmer edit section *** (Student CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("StudentE", new string[] {
            "studentName as \'Имя студента\'",
            "age as \'Возраст\'",
            "sex as \'Пол\'",
            "Group as \'Группа\'",
            "Group.groupName as \'Название группы\'"}, Hidden=new string[] {
            "Group.groupName"})]
    [MasterViewDefineAttribute("StudentE", "Group", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "groupName")]
    [View("StudentL", new string[] {
            "studentName as \'Имя студента\'",
            "age as \'Возраст\'",
            "sex as \'Пол\'",
            "Group.groupName as \'Группа\'"})]
    public class Student : ICSSoft.STORMNET.DataObject
    {
        
        private int fage;
        
        private string fsex;
        
        private string fstudentName;
        
        private IIS.FlexberrySampleLogging.Group fGroup;
        
        // *** Start programmer edit section *** (Student CustomMembers)

        // *** End programmer edit section *** (Student CustomMembers)

        
        /// <summary>
        /// age.
        /// </summary>
        // *** Start programmer edit section *** (Student.age CustomAttributes)

        // *** End programmer edit section *** (Student.age CustomAttributes)
        public virtual int age
        {
            get
            {
                // *** Start programmer edit section *** (Student.age Get start)

                // *** End programmer edit section *** (Student.age Get start)
                int result = this.fage;
                // *** Start programmer edit section *** (Student.age Get end)

                // *** End programmer edit section *** (Student.age Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.age Set start)

                // *** End programmer edit section *** (Student.age Set start)
                this.fage = value;
                // *** Start programmer edit section *** (Student.age Set end)

                // *** End programmer edit section *** (Student.age Set end)
            }
        }
        
        /// <summary>
        /// sex.
        /// </summary>
        // *** Start programmer edit section *** (Student.sex CustomAttributes)

        // *** End programmer edit section *** (Student.sex CustomAttributes)
        [StrLen(255)]
        public virtual string sex
        {
            get
            {
                // *** Start programmer edit section *** (Student.sex Get start)

                // *** End programmer edit section *** (Student.sex Get start)
                string result = this.fsex;
                // *** Start programmer edit section *** (Student.sex Get end)

                // *** End programmer edit section *** (Student.sex Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.sex Set start)

                // *** End programmer edit section *** (Student.sex Set start)
                this.fsex = value;
                // *** Start programmer edit section *** (Student.sex Set end)

                // *** End programmer edit section *** (Student.sex Set end)
            }
        }
        
        /// <summary>
        /// studentName.
        /// </summary>
        // *** Start programmer edit section *** (Student.studentName CustomAttributes)

        // *** End programmer edit section *** (Student.studentName CustomAttributes)
        [StrLen(255)]
        public virtual string studentName
        {
            get
            {
                // *** Start programmer edit section *** (Student.studentName Get start)

                // *** End programmer edit section *** (Student.studentName Get start)
                string result = this.fstudentName;
                // *** Start programmer edit section *** (Student.studentName Get end)

                // *** End programmer edit section *** (Student.studentName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.studentName Set start)

                // *** End programmer edit section *** (Student.studentName Set start)
                this.fstudentName = value;
                // *** Start programmer edit section *** (Student.studentName Set end)

                // *** End programmer edit section *** (Student.studentName Set end)
            }
        }
        
        /// <summary>
        /// Student.
        /// </summary>
        // *** Start programmer edit section *** (Student.Group CustomAttributes)

        // *** End programmer edit section *** (Student.Group CustomAttributes)
        [PropertyStorage(new string[] {
                "Group"})]
        public virtual IIS.FlexberrySampleLogging.Group Group
        {
            get
            {
                // *** Start programmer edit section *** (Student.Group Get start)

                // *** End programmer edit section *** (Student.Group Get start)
                IIS.FlexberrySampleLogging.Group result = this.fGroup;
                // *** Start programmer edit section *** (Student.Group Get end)

                // *** End programmer edit section *** (Student.Group Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Student.Group Set start)

                // *** End programmer edit section *** (Student.Group Set start)
                this.fGroup = value;
                // *** Start programmer edit section *** (Student.Group Set end)

                // *** End programmer edit section *** (Student.Group Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "StudentE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentE", typeof(IIS.FlexberrySampleLogging.Student));
                }
            }
            
            /// <summary>
            /// "StudentL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View StudentL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("StudentL", typeof(IIS.FlexberrySampleLogging.Student));
                }
            }
        }
    }
}
